/**
 * Noise against attack, side by side.
 *
 * The claim is that the same mean QBER can come from a noisy fibre or from an
 * eavesdropper. The screen proves it rather than asserting it: both sides are
 * **real runs** on the real engine, and the bars show what came back.
 *
 * The two sides are set by their own physical parameter — a fibre length on the
 * left, an intercepted fraction on the right — rather than by a shared target.
 * "Ten kilometres of fibre against an eavesdropper touching half the qubits" is
 * a statement about the world; "both sides at eleven percent" is a statement
 * about the answer, and handing the reader the coincidence is weaker than
 * letting them arrive at it. `Match the QBERs` is one button away, and the gap
 * between the two means is on screen the whole time.
 *
 * WHAT THE SECOND READING IS DEPENDS ON THE PROTOCOL, and that is the point of
 * having both here. In BB84 the per-basis split tells the two causes apart: the
 * damping hits Z about twice as hard as X, while an intercept-resend errs
 * equally in both. E91 has no such split, and S does not stand in for it —
 * measured at equal QBER, the gap between the two S values sits inside the
 * sampling uncertainty. So the same screen shows a diagnosis in one protocol
 * and its absence in the other, which is a stronger thing to show than either
 * alone.
 */

import { useCallback, useState } from "react";

import { ApiError } from "../../api/client";
import type { ProtocolKind, RunResult, TrialResult } from "../../api/contract";
import { useRun } from "../../api/useRun";
import { TopBarControls } from "../../components/ScreenTabs";
import { BarChart } from "../../components/BarChart";
import { Chip, Kicker, RunButton, Segmented, Slider } from "../../components/controls";
import { Banner } from "../../components/Banner";
import { SideSkeleton } from "../../components/Skeleton";
import { usePlugins } from "../../api/queries";
import { rollSeed, SeedField } from "../../components/SeedField";
import { Sphere } from "../../components/Sphere";
import { useCopy } from "../../i18n/useCopy";
import { measured } from "../../lib/nullable";
import { gammaFromLength } from "../../lib/physics";

const QUBITS = 4000;
/**
 * A fresh seed per visit, not a fixed one.
 *
 * Reproducibility is not lost by this: the seed is a control and every exported
 * figure prints it, so any picture can be regenerated by typing it back in.
 * What a fixed default bought was that two people opening the page saw the same
 * thing — worth little here, against the cost that pressing Run twice looked
 * like it had done nothing.
 *
 * Both sides of one comparison always share it, which is what keeps the
 * physics as the only difference between them.
 */
interface SideView {
  result: RunResult;
  first: TrialResult;
}

/** The two-node scene above each panel: the same material as the whiteboard. */
function MiniScene({
  withEve,
  withSource,
  accent,
  label,
  sourceLabel,
}: {
  withEve: boolean;
  withSource: boolean;
  accent: string;
  label: string;
  sourceLabel: string;
}) {
  // Alice and Bob at the ends; in E91 the source between them, and Eve — when
  // present — on the arm she breaks. Leaving the source out drew a protocol
  // nobody runs.
  const nodes = withSource
    ? [
        { color: "var(--blue)", left: "12%", d: 38, name: "Alice" },
        { color: "var(--purple)", left: withEve ? "56%" : "50%", d: 38, name: sourceLabel },
        { color: "var(--mint)", left: "88%", d: 38, name: "Bob" },
        ...(withEve ? [{ color: "var(--red)", left: "33%", d: 30, name: "Eve" }] : []),
      ]
    : [
        { color: "var(--blue)", left: "14%", d: 40, name: "Alice" },
        { color: "var(--mint)", left: "86%", d: 40, name: "Bob" },
        ...(withEve ? [{ color: "var(--red)", left: "50%", d: 30, name: "Eve" }] : []),
      ];

  return (
    <div
      style={{
        position: "relative",
        height: 104,
        borderRadius: 14,
        border: "1px solid var(--line)",
        background: `radial-gradient(80% 120% at 50% 30%, color-mix(in oklab, ${accent} 8%, var(--sky)) 0%, var(--sky) 70%)`,
        overflow: "hidden",
      }}
    >
      <div
        style={{
          position: "absolute",
          left: "14%",
          right: "14%",
          top: "50%",
          height: 2,
          transform: "translateY(-50%)",
          borderRadius: 2,
          background: `linear-gradient(90deg, var(--blue), ${withEve ? "var(--red)" : "var(--mint)"} 50%, var(--mint))`,
          opacity: 0.75,
          boxShadow: `0 0 14px -4px ${accent}`,
          zIndex: 1,
        }}
      />
      {nodes.map((node) => (
        <div
          key={node.name}
          style={{
            position: "absolute",
            left: node.left,
            top: "50%",
            transform: "translate(-50%, -50%)",
            display: "flex",
            flexDirection: "column",
            alignItems: "center",
            gap: 8,
            zIndex: 3,
          }}
        >
          <Sphere color={node.color} d={node.d} />
          <span
            style={{
              fontSize: 11.5,
              fontWeight: 500,
              color: "var(--fg-2)",
              whiteSpace: "nowrap",
              textShadow: "0 1px 3px var(--shadow)",
            }}
          >
            {node.name}
          </span>
        </div>
      ))}
      <span
        className="mono"
        style={{
          position: "absolute",
          left: "50%",
          bottom: 8,
          transform: "translateX(-50%)",
          fontSize: 9.5,
          color: "var(--fg-3)",
          whiteSpace: "nowrap",
          zIndex: 4,
        }}
      >
        {label}
      </span>
    </div>
  );
}

/**
 * Errors laid out position by position, from the run's own views.
 *
 * Each cell is a sifted position: tall and red where Alice and Bob disagree,
 * short and grey where they do not. Split per basis, the noise side shows about
 * twice as many tall cells in the Z row as in the X row while the attack side
 * shows the same in both — the argument made visible rather than stated.
 */
function ErrorStrip({
  name,
  color,
  positions,
  errorLabel,
  okLabel,
}: {
  name: string;
  color: string;
  positions: boolean[];
  errorLabel: string;
  okLabel: string;
}) {
  const errors = positions.filter(Boolean).length;
  return (
    <div style={{ display: "grid", gridTemplateColumns: "minmax(0,1fr) auto", alignItems: "center", gap: 8 }}>
      <span className="mono" style={{ fontSize: 11, color, whiteSpace: "nowrap" }}>
        {name}
      </span>
      <span className="mono" style={{ fontSize: 11, color: "var(--fg-2)", textAlign: "right", whiteSpace: "nowrap" }}>
        {errors}/{positions.length}
      </span>
      <div style={{ gridColumn: "1 / -1", display: "flex", gap: 1, minWidth: 0, height: 24, alignItems: "center" }}>
        {positions.map((bad, index) => (
          <span
            key={index}
            title={bad ? errorLabel : okLabel}
            style={{
              flex: "1 1 0",
              minWidth: 2,
              height: bad ? 22 : 8,
              alignSelf: "center",
              borderRadius: 2,
              background: bad ? "var(--red)" : "var(--line-2)",
              boxShadow: bad ? "0 0 8px -3px var(--red)" : "none",
              transition: "height .5s cubic-bezier(.32,.72,0,1), background .5s ease",
            }}
          />
        ))}
      </div>
    </div>
  );
}

/** Whether each sifted position in one basis came out wrong. */
function errorsInBasis(trial: TrialResult, basis: number | null, limit: number): boolean[] {
  const views = trial.views;
  if (!views) return [];
  // Alice prepares bits in BB84 and records outcomes in E91: the same row of
  // the same length, under a different name.
  const aliceBits = views.alice.bits ?? views.alice.outcomes ?? [];
  const bobOutcomes = views.bob.outcomes ?? [];
  const bases = views.alice.bases ?? [];
  const out: boolean[] = [];
  for (let index = 0; index < views.survived_sifting.length && out.length < limit; index++) {
    if (!views.survived_sifting[index]) continue;
    if (basis !== null && bases[index] !== basis) continue;
    out.push(aliceBits[index] !== bobOutcomes[index]);
  }
  return out;
}

export default function Comparison() {
  const t = useCopy();
  const noise = useRun();
  const attack = useRun();
  const backend = usePlugins();

  const [protocol, setProtocol] = useState<ProtocolKind>("bb84");
  const [km, setKm] = useState(7.5);
  const [fraction, setFraction] = useState(0.44);
  const [seed, setSeed] = useState(rollSeed);
  const [failure, setFailure] = useState<string | null>(null);
  /** The parameters the runs on screen were actually launched with. */
  const [shown, setShown] = useState<{ km: number; gamma: number; fraction: number } | null>(null);

  const isBB84 = protocol === "bb84";
  const gamma = gammaFromLength(km);

  /**
   * Switching protocol throws the results away.
   *
   * Two BB84 runs left on screen under an E91 heading would be read as E91
   * results — and read against the wrong second observable, since the panels
   * change with the protocol. Better an empty frame that says nothing than a
   * full one that says something false.
   *
   * Nothing runs on arrival either: each side is a four thousand qubit
   * simulation, and starting two of them because a page was opened spends a
   * reader's time on a question they have not asked yet.
   */
  const reset = noise.reset;
  const resetAttack = attack.reset;
  const chooseProtocol = useCallback(
    (next: ProtocolKind) => {
      if (next === protocol) return;
      setProtocol(next);
      setShown(null);
      reset();
      resetAttack();
    },
    [protocol, reset, resetAttack],
  );

  const launchNoise = noise.launch;
  const launchAttack = attack.launch;

  const launch = useCallback(async () => {
    setFailure(null);
    setShown({ km, gamma, fraction });
    const base = { protocol, n_qubits: QUBITS, trials: 1, seed };
    try {
      // Both sides start together: the server allows several concurrent runs,
      // and sequencing them would double a wait nothing requires.
      await Promise.all([
        launchNoise({
          ...base,
          channel: { kind: "amplitude_damping", gamma: Number(gamma.toFixed(4)) },
          attack: { kind: "none" },
        }),
        launchAttack({
          ...base,
          channel: { kind: "ideal" },
          attack: { kind: "intercept_resend", fraction: Number(fraction.toFixed(3)) },
        }),
      ]);
    } catch (error) {
      setFailure(error instanceof ApiError ? (error.isBusy ? t.busy : error.detail) : String(error));
    }
  }, [fraction, gamma, km, launchAttack, launchNoise, protocol, seed, t]);

  const busy = noise.isRunning || attack.isRunning;

  const sides: (SideView | null)[] = [
    noise.result && noise.trials[0] ? { result: noise.result, first: noise.trials[0] } : null,
    attack.result && attack.trials[0] ? { result: attack.result, first: attack.trials[0] } : null,
  ];

  const ticks = [0, 0.05, 0.1, 0.15, 0.2, 0.25];
  const cells = 36;

  return (
    <div style={{ minHeight: "100vh", background: "var(--bg)", color: "var(--fg)" }}>
      <header
        style={{
          position: "sticky",
          top: 0,
          zIndex: 5,
          display: "flex",
          alignItems: "center",
          gap: 18,
          flexWrap: "wrap",
          padding: "14px 26px",
          borderBottom: "1px solid var(--line)",
          background: "color-mix(in oklab, var(--bg-2) 92%, transparent)",
          backdropFilter: "blur(14px)",
        }}
      >
        <div style={{ display: "flex", flexDirection: "column", gap: 2, minWidth: 0 }}>
          <span style={{ fontSize: 15, fontWeight: 600, letterSpacing: "-.02em", whiteSpace: "nowrap" }}>
            {t.comparisonTitle}
          </span>
          <span className="mono" style={{ fontSize: 10.5, color: "var(--fg-3)", whiteSpace: "nowrap" }}>
            {isBB84 ? "BB84" : "E91"} · {shown ? `${shown.km.toFixed(1)} km · F ${shown.fraction.toFixed(2)}` : "—"}
            {" · "}seed {seed} · n = {QUBITS}
          </span>
        </div>
        <div style={{ flex: 1 }} />
        <TopBarControls />
      </header>

      <main style={{ padding: 26, display: "flex", flexDirection: "column", gap: 22, maxWidth: 1500, margin: "0 auto" }}>
        {backend.isError && <Banner tone="error">{t.backendDown}</Banner>}

        <section
          style={{
            display: "flex",
            flexWrap: "wrap",
            gap: 20,
            alignItems: "flex-end",
            padding: "18px 20px",
            border: "1px solid var(--line)",
            borderRadius: 16,
            background: "var(--panel)",
            boxShadow: "inset 0 1px 0 var(--hi)",
          }}
        >
          <div style={{ display: "flex", flexDirection: "column", gap: 8, flex: "0 0 190px" }}>
            <Kicker>{t.protocol}</Kicker>
            <Segmented<ProtocolKind>
              wide
              label={t.protocol}
              options={[
                { id: "bb84", label: "BB84" },
                { id: "e91", label: "E91" },
              ]}
              value={protocol}
              onChange={chooseProtocol}
              disabled={busy}
            />
          </div>

          {/* One control per side, each the parameter that side is about. */}
          <div style={{ display: "flex", flexDirection: "column", gap: 8, flex: "1 1 280px", minWidth: 250 }}>
            <Slider
              label={t.fibreControl}
              display={`${km.toFixed(1)} km · γ ${gamma.toFixed(3)}`}
              min={0}
              max={20}
              step={0.5}
              value={km}
              onChange={setKm}
            disabled={busy}
            />
          </div>
          <div style={{ display: "flex", flexDirection: "column", gap: 8, flex: "1 1 280px", minWidth: 250 }}>
            <Slider
              label={t.fractionControl}
              display={`${(fraction * 100).toFixed(0)} %`}
              min={0}
              max={1}
              step={0.01}
              value={fraction}
              onChange={setFraction}
            disabled={busy}
            />
          </div>

          <div style={{ display: "flex", flexDirection: "column", gap: 8, flex: "0 0 200px" }}>
            <SeedField
              value={seed}
              onChange={(next) => {
                setSeed(next);
                setShown(null);
                reset();
                resetAttack();
              }}
              disabled={busy}
            />
          </div>

          <div style={{ display: "flex", flexDirection: "column", gap: 8, flex: "0 0 230px" }}>
            {/* A button rather than a live slider: each side is a four thousand
                qubit simulation, and re-running two of them on every pixel of
                drag would make the control unusable. */}
            <RunButton
              label={t.runNow}
              stopLabel={t.stop}
              busy={busy}
              onClick={launch}
              onStop={() => {
                // Two runs in flight, so both are told: stopping one and
                // leaving the other going would leave half a comparison.
                noise.cancel();
                attack.cancel();
              }}
            />
            {(failure || noise.error || attack.error) && (
              <span style={{ fontSize: 11, color: "var(--red)", lineHeight: 1.5 }}>
                {failure ?? noise.error ?? attack.error}
              </span>
            )}
          </div>
        </section>

        <section
          style={{
            display: "grid",
            gridTemplateColumns: "repeat(auto-fit, minmax(380px, 1fr))",
            gap: 16,
            alignItems: "stretch",
          }}
        >
          {[0, 1].map((index) => {
            const meta = t.sides[index]!;
            const isNoise = index === 0;
            const accent = isNoise ? "var(--blue)" : "var(--red)";
            const side = sides[index];
            const basis = side?.first.qber_by_basis ?? null;
            const z = basis?.rectilinear ?? null;
            const x = basis?.diagonal ?? null;
            const mean = side?.result.qber_mean ?? null;
            const ratio = measured(z) && measured(x) && x > 0 ? z / x : null;

            // BB84 reports the mean and the two bases; E91 has no bases to
            // report, so it reports the mean alone and carries S in the stat
            // row instead.
            const bars = [
              ...(measured(mean)
                ? [{ label: t.barMean, value: mean, color: accent, text: `${(mean * 100).toFixed(2)} %` }]
                : []),
              ...(isBB84 && measured(z)
                ? [{ label: t.barZ, value: z, color: "var(--blue)", text: `${(z * 100).toFixed(2)} %` }]
                : []),
              ...(isBB84 && measured(x)
                ? [{ label: t.barX, value: x, color: "var(--purple)", text: `${(x * 100).toFixed(2)} %` }]
                : []),
            ];

            const chsh = side?.result.chsh_mean ?? null;
            const sigma = side?.first.chsh_sigma ?? null;
            const chshBound = measured(sigma) ? 2 + 3 * sigma : null;

            const strips = !side
              ? []
              : isBB84
                ? [
                    { name: t.zRow, color: "var(--blue)", positions: errorsInBasis(side.first, 0, cells) },
                    { name: t.xRow, color: "var(--purple)", positions: errorsInBasis(side.first, 1, cells) },
                  ]
                : [{ name: t.stripAll, color: "var(--fg-2)", positions: errorsInBasis(side.first, null, cells) }];

            return (
              <div
                key={index}
                style={{
                  display: "flex",
                  flexDirection: "column",
                  gap: 18,
                  padding: 22,
                  border: `1px solid color-mix(in oklab, ${accent} 26%, var(--line))`,
                  borderRadius: 18,
                  background: "var(--panel)",
                  boxShadow: "0 26px 60px -46px #000, inset 0 1px 0 var(--hi)",
                }}
              >
                <div style={{ display: "flex", alignItems: "flex-start", justifyContent: "space-between", gap: 14 }}>
                  <div style={{ display: "flex", flexDirection: "column", gap: 5, minWidth: 0 }}>
                    <span
                      className="mono"
                      style={{ fontSize: 10.5, letterSpacing: ".12em", color: accent, fontWeight: 500 }}
                    >
                      {meta.kicker}
                    </span>
                    <span style={{ fontSize: 17, fontWeight: 600, letterSpacing: "-.02em" }}>{meta.name}</span>
                    <span style={{ fontSize: 12.5, lineHeight: 1.55, color: "var(--fg-2)" }}>{meta.desc}</span>
                  </div>
                  <Chip color={isNoise ? "var(--mint)" : "var(--red)"}>{meta.tag}</Chip>
                </div>

                <MiniScene
                  withEve={!isNoise}
                  withSource={!isBB84}
                  sourceLabel={t.roles.source}
                  accent={accent}
                  label={
                    isNoise
                      ? `damping γ ${(shown?.gamma ?? 0).toFixed(3)} · ${(shown?.km ?? 0).toFixed(1)} km`
                      : `${t.ideal.toLowerCase()} · F ${(shown?.fraction ?? 0).toFixed(2)}`
                  }
                />

                <div
                  style={{
                    display: "flex",
                    alignItems: "flex-end",
                    justifyContent: "space-between",
                    gap: 14,
                    padding: "14px 16px",
                    border: "1px solid var(--line-2)",
                    borderRadius: 13,
                    background: "var(--panel-2)",
                  }}
                >
                  <div style={{ display: "flex", flexDirection: "column", gap: 3 }}>
                    <span
                      className="mono"
                      style={{ fontSize: 10, letterSpacing: ".1em", textTransform: "uppercase", color: "var(--fg-3)" }}
                    >
                      {t.meanQber}
                    </span>
                    <span className="mono" style={{ fontSize: 30, fontWeight: 600, lineHeight: 1, color: "var(--fg)" }}>
                      {measured(mean) ? `${(mean * 100).toFixed(2)} %` : "—"}
                    </span>
                  </div>
                  <div style={{ display: "flex", flexDirection: "column", gap: 3, textAlign: "right" }}>
                    <span
                      className="mono"
                      style={{ fontSize: 10, letterSpacing: ".1em", textTransform: "uppercase", color: "var(--fg-3)" }}
                    >
                      {isBB84 ? t.asymShort : t.chsh}
                    </span>
                    {isBB84 ? (
                      <span
                        className="mono"
                        style={{
                          fontSize: 22,
                          fontWeight: 600,
                          lineHeight: 1,
                          color: ratio === null ? "var(--fg-3)" : ratio > 1.5 ? "var(--blue)" : "var(--red)",
                        }}
                      >
                        {ratio === null ? "—" : `${ratio.toFixed(2)}×`}
                      </span>
                    ) : (
                      <>
                        <span
                          className="mono"
                          style={{
                            fontSize: 22,
                            fontWeight: 600,
                            lineHeight: 1,
                            color: !measured(chsh)
                              ? "var(--fg-3)"
                              : measured(chshBound) && chsh > chshBound
                                ? "var(--mint)"
                                : "var(--red)",
                          }}
                        >
                          {measured(chsh) ? chsh.toFixed(3) : "—"}
                        </span>
                        <span className="mono" style={{ fontSize: 10, color: "var(--fg-3)" }}>
                          {measured(chshBound) ? `2 + kσ = ${chshBound.toFixed(3)}` : ""}
                        </span>
                      </>
                    )}
                  </div>
                </div>

                <div style={{ display: "flex", flexDirection: "column", gap: 12 }}>
                  <Kicker>{isBB84 ? t.chartTitle : t.abortTrigger}</Kicker>
                  {bars.length === 0 && <SideSkeleton active={busy} bars={3} />}
                  {bars.length > 0 && (
                    <BarChart
                      series={bars}
                      max={0.25}
                      ticks={ticks}
                      formatTick={(value) => `${(value * 100).toFixed(0)} %`}
                      // In BB84 the rule is this side's own mean, so the two
                      // per-basis bars are read against it: damping puts Z well
                      // to its right and X to its left, interception puts both
                      // on it. In E91 there is a single bar and nothing to read
                      // it against but the acceptance threshold.
                      // Only in BB84, and only on this side's own mean, so the
                      // two per-basis bars are read against it. E91 gets no
                      // rule at all: its error rate decides nothing, and a line
                      // across it would invite reading it as a verdict.
                      rule={
                        isBB84
                          ? {
                              value: mean ?? 0,
                              color: "var(--orange)",
                              label: `${t.trialsMean} ${((mean ?? 0) * 100).toFixed(2)} %`,
                            }
                          : undefined
                      }
                      axisTitle={t.axisQber}
                    />
                  )}
                </div>

                <div style={{ display: "flex", flexDirection: "column", gap: 9 }}>
                  <Kicker>{isBB84 ? t.stripTitle : t.stripTitlePlain}</Kicker>
                  {strips.map((strip) => (
                    <ErrorStrip
                      key={strip.name}
                      name={strip.name}
                      color={strip.color}
                      positions={strip.positions}
                      errorLabel={t.stripError}
                      okLabel={t.stripOk}
                    />
                  ))}
                  {isBB84 && (
                    <span style={{ fontSize: 11, lineHeight: 1.5, color: "var(--fg-3)" }}>{meta.note}</span>
                  )}
                </div>

                <div style={{ display: "flex", flexWrap: "wrap", gap: 8, marginTop: "auto" }}>
                  {(isNoise
                    ? [
                        `${t.fibreControl}: ${(shown?.km ?? 0).toFixed(1)} km`,
                        `γ = ${(shown?.gamma ?? 0).toFixed(3)}`,
                      ]
                    : [
                        `${t.channel}: ${t.ideal.toLowerCase()}`,
                        `F = ${(shown?.fraction ?? 0).toFixed(2)}`,
                        "intercept-resend",
                        ...(measured(side?.first.eavesdropper_knowledge)
                          ? [`Eve ${(side!.first.eavesdropper_knowledge! * 100).toFixed(0)} %`]
                          : []),
                      ].flat()
                  ).map((label) => (
                    <Chip key={label} color={isNoise ? "var(--grey)" : "var(--orange)"}>
                      {label}
                    </Chip>
                  ))}
                </div>
              </div>
            );
          })}
        </section>

        <section
          style={{
            display: "flex",
            alignItems: "center",
            gap: 14,
            padding: "14px 20px",
            border: "1px solid var(--line)",
            borderRadius: 16,
            background: "var(--panel)",
            boxShadow: "inset 0 1px 0 var(--hi)",
          }}
        >
          <span
            style={{
              width: 8,
              height: 8,
              borderRadius: "50%",
              background: "var(--orange)",
              boxShadow: "0 0 9px -1px var(--orange)",
              flex: "none",
              animation: "qbreath 3s ease-in-out infinite",
            }}
          />
          <span style={{ fontSize: 13.5, lineHeight: 1.6, color: "var(--fg)" }}>
            {isBB84 ? t.bb84Fingerprint : t.e91NoFingerprint}
          </span>
        </section>
      </main>
    </div>
  );
}
