/**
 * The run's seed, and a way to roll it again.
 *
 * Every screen that launches something needs this, and for two opposite
 * reasons. Held fixed, a figure is reproducible: a chart exported with
 * `seed 20260818` printed on it can be regenerated by anyone, and comparing two
 * configurations is only meaningful when the dice are the same for both — else
 * a difference could have come from the parameter or from the sampling.
 *
 * Rolled again, it shows how much the answer moves on its own. That is the
 * question behind every number read off a curve: if the threshold crossing
 * shifts by two kilometres between seeds, it does not belong in a report
 * without saying so.
 *
 * Both are needed, which is why this is a value with a button and not a
 * checkbox for "random".
 */

import { useCopy } from "../i18n/useCopy";

/** A fresh eight-digit seed, wide enough that repeats are not a worry. */
export const rollSeed = (): number => Math.floor(Math.random() * 9e7) + 1e7;

export function SeedField({
  value,
  onChange,
  disabled = false,
}: {
  value: number;
  onChange: (seed: number) => void;
  disabled?: boolean;
}) {
  const t = useCopy();

  return (
    <div style={{ display: "flex", flexDirection: "column", gap: 6 }}>
      <div style={{ display: "flex", justifyContent: "space-between", alignItems: "baseline" }}>
        <span style={{ fontSize: 13, color: disabled ? "var(--fg-3)" : "var(--fg-2)" }}>{t.seed}</span>
        <span style={{ fontSize: 11, color: "var(--fg-3)" }}>{t.seedRequired}</span>
      </div>
      <div style={{ display: "flex", gap: 7 }}>
        <input
          value={value}
          aria-label={t.seed}
          data-testid="seed-input"
          disabled={disabled}
          onChange={(event) => onChange(parseInt(event.target.value.replace(/\D/g, "") || "0", 10))}
          className="mono"
          style={{
            flex: 1,
            minWidth: 0,
            background: "var(--panel)",
            border: "1px solid var(--line)",
            borderRadius: 9,
            padding: "9px 11px",
            color: "var(--fg)",
            fontSize: 12.5,
            outline: "none",
          }}
        />
        <button
          type="button"
          title={t.randomize}
          aria-label={t.randomize}
          data-testid="seed-randomize"
          disabled={disabled}
          onClick={() => onChange(rollSeed())}
          style={{
            flex: "none",
            width: 38,
            border: "1px solid var(--line)",
            borderRadius: 9,
            background: "var(--panel-2)",
            color: "var(--fg-2)",
            cursor: disabled ? "default" : "pointer",
            fontSize: 14,
            boxShadow: "inset 0 1px 0 var(--hi)",
          }}
        >
          ⟳
        </button>
      </div>
    </div>
  );
}
